package com.truckify.app.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Onboarding : Screen("onboarding")
    object RoleSelection : Screen("role_selection")
    object Welcome : Screen("welcome")
    object Login : Screen("login")
    object PhoneLogin : Screen("phone_login")
    object Signup : Screen("signup")
    object Home : Screen("home")
    object Notifications : Screen("notifications")
    object Payments : Screen("payments")
    object Drivers : Screen("drivers")
    object Routes : Screen("routes")
    object Search : Screen("search")
    object Orders : Screen("orders")
    object History : Screen("history")
    object Chatbot : Screen("chatbot")
    object LoadDetails : Screen("load_details")
    object Verification : Screen("verification")
    object QrShow : Screen("qr_show")
    object QrScan : Screen("qr_scan")
    object OtpVerify : Screen("otp_verify")
    object Tracking : Screen("tracking")
    object Settings : Screen("settings")
    object Profile : Screen("profile")
    object Create : Screen("create")
    object Matching : Screen("matching")
    object FleetHeatmap : Screen("fleet_heatmap")
    object ShipmentChat : Screen("shipment_chat")
    object ExpenseTracker : Screen("expense_tracker")
    object EditProfile : Screen("edit_profile")
    object Terms : Screen("terms")
    object Support : Screen("support")
    object Confirming : Screen("confirming")
}
